table mart_adjacent_pair_metrics

	column from_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: from_as_of_date
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"from_as_of_date"}]

	column from_release_revision
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: from_release_revision
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"from_release_revision"}]

	column from_revision_fingerprint
		dataType: string
		summarizeBy: none
		sourceColumn: from_revision_fingerprint
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"from_revision_fingerprint"}]

	column to_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: to_as_of_date
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"to_as_of_date"}]

	column to_release_revision
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: to_release_revision
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"to_release_revision"}]

	column to_revision_fingerprint
		dataType: string
		summarizeBy: none
		sourceColumn: to_revision_fingerprint
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"to_revision_fingerprint"}]

	column gap_days
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: gap_days
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"gap_days"}]

	column starting_delinquent_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: starting_delinquent_count
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"starting_delinquent_count"}]

	column ending_published_delinquent_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: ending_published_delinquent_count
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"ending_published_delinquent_count"}]

	column observed_exit_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: observed_exit_count
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"observed_exit_count"}]

	column still_delinquent_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: still_delinquent_count
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"still_delinquent_count"}]

	column not_observed_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: not_observed_count
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"not_observed_count"}]

	column matched_observed_entry_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: matched_observed_entry_count
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"matched_observed_entry_count"}]

	column newly_observed_delinquent_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: newly_observed_delinquent_count
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"newly_observed_delinquent_count"}]

	column total_entrant_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: total_entrant_count
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"total_entrant_count"}]

	column net_delinquent_movement
		dataType: string
		summarizeBy: none
		sourceColumn: net_delinquent_movement
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"net_delinquent_movement"}]

	column observed_exit_denominator_id
		dataType: string
		summarizeBy: none
		sourceColumn: observed_exit_denominator_id
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"observed_exit_denominator_id"}]

	column observed_exit_proportion
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: observed_exit_proportion
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"observed_exit_proportion"}]

	column largest_transition_from_status
		dataType: string
		summarizeBy: none
		sourceColumn: largest_transition_from_status
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"largest_transition_from_status"}]

	column largest_transition_to_status
		dataType: string
		summarizeBy: none
		sourceColumn: largest_transition_to_status
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"largest_transition_to_status"}]

	column largest_transition_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: largest_transition_count
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"largest_transition_count"}]

	column matched_entry_denominator_id
		dataType: string
		summarizeBy: none
		sourceColumn: matched_entry_denominator_id
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"matched_entry_denominator_id"}]

	column total_entrant_denominator_id
		dataType: string
		summarizeBy: none
		sourceColumn: total_entrant_denominator_id
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"total_entrant_denominator_id"}]

	column observed_exit_wilson_95_lower
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: observed_exit_wilson_95_lower
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"observed_exit_wilson_95_lower"}]

	column observed_exit_wilson_95_upper
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: observed_exit_wilson_95_upper
		annotation CalicoBaseLineage = [{"table_name":"mart_adjacent_pair_metrics","column_name":"observed_exit_wilson_95_upper"}]

	partition mart_adjacent_pair_metrics = m
		mode: import
		source =
			let
			    Source = Csv.Document(Web.Contents(PublishedBaseUrl, [RelativePath="exports/mart_adjacent_pair_metrics.csv"]), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=false]),
			    Required = {"from_as_of_date", "from_release_revision", "from_revision_fingerprint", "to_as_of_date", "to_release_revision", "to_revision_fingerprint", "gap_days", "starting_delinquent_count", "ending_published_delinquent_count", "observed_exit_count", "still_delinquent_count", "not_observed_count", "matched_observed_entry_count", "newly_observed_delinquent_count", "total_entrant_count", "net_delinquent_movement", "observed_exit_denominator_id", "observed_exit_proportion", "largest_transition_from_status", "largest_transition_to_status", "largest_transition_count", "matched_entry_denominator_id", "total_entrant_denominator_id", "observed_exit_wilson_95_lower", "observed_exit_wilson_95_upper"},
			    Shape = if Table.ColumnNames(Headers) <> Required then error "mart_adjacent_pair_metrics.source_shape" else Headers,
			    Selected = Table.SelectColumns(Shape, Required, MissingField.Error),
			    Typed = Table.TransformColumnTypes(Selected, {{"from_as_of_date", type date}, {"from_release_revision", Int64.Type}, {"from_revision_fingerprint", type text}, {"to_as_of_date", type date}, {"to_release_revision", Int64.Type}, {"to_revision_fingerprint", type text}, {"gap_days", Int64.Type}, {"starting_delinquent_count", Int64.Type}, {"ending_published_delinquent_count", Int64.Type}, {"observed_exit_count", Int64.Type}, {"still_delinquent_count", Int64.Type}, {"not_observed_count", Int64.Type}, {"matched_observed_entry_count", Int64.Type}, {"newly_observed_delinquent_count", Int64.Type}, {"total_entrant_count", Int64.Type}, {"net_delinquent_movement", type text}, {"observed_exit_denominator_id", type text}, {"observed_exit_proportion", type number}, {"largest_transition_from_status", type text}, {"largest_transition_to_status", type text}, {"largest_transition_count", Int64.Type}, {"matched_entry_denominator_id", type text}, {"total_entrant_denominator_id", type text}, {"observed_exit_wilson_95_lower", type number}, {"observed_exit_wilson_95_upper", type number}}, "en-US")
			in
			    Typed
