table mart_spell_censoring_summary

	column terminal_state
		dataType: string
		summarizeBy: none
		sourceColumn: terminal_state
		annotation CalicoBaseLineage = [{"table_name":"mart_spell_censoring_summary","column_name":"terminal_state"}]

	column spell_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: spell_count
		annotation CalicoBaseLineage = [{"table_name":"mart_spell_censoring_summary","column_name":"spell_count"}]

	partition mart_spell_censoring_summary = m
		mode: import
		source =
			let
			    Source = Csv.Document(Web.Contents(PublishedBaseUrl, [RelativePath="exports/mart_spell_censoring_summary.csv"]), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=false]),
			    Required = {"terminal_state", "spell_count"},
			    Shape = if Table.ColumnNames(Headers) <> Required then error "mart_spell_censoring_summary.source_shape" else Headers,
			    Selected = Table.SelectColumns(Shape, Required, MissingField.Error),
			    Typed = Table.TransformColumnTypes(Selected, {{"terminal_state", type text}, {"spell_count", Int64.Type}}, "en-US")
			in
			    Typed
