table mart_claim_support
	lineageTag: 76c3d071-d23e-4170-bf98-260c63a448c6

	column claim_support_version
		dataType: string
		lineageTag: 74564df7-b791-4361-8599-dd1cca02832f
		summarizeBy: none
		sourceColumn: claim_support_version

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"claim_support_version"}]

	column from_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 0a19641a-354e-4b1e-a00c-a69b4556c864
		summarizeBy: none
		sourceColumn: from_as_of_date

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"from_as_of_date"}]

		annotation UnderlyingDateTimeDataType = Date

	column from_release_revision
		dataType: int64
		formatString: 0
		lineageTag: 736bb197-8355-4a7d-8719-ec76178bf2c0
		summarizeBy: none
		sourceColumn: from_release_revision

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"from_release_revision"}]

	column from_revision_fingerprint
		dataType: string
		lineageTag: 675d2c8a-71b4-42f0-b1e8-208ef8e482a0
		summarizeBy: none
		sourceColumn: from_revision_fingerprint

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"from_revision_fingerprint"}]

	column to_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 806dc0ef-75ae-4a08-80f1-3645cf9b9f2a
		summarizeBy: none
		sourceColumn: to_as_of_date

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"to_as_of_date"}]

		annotation UnderlyingDateTimeDataType = Date

	column to_release_revision
		dataType: int64
		formatString: 0
		lineageTag: a2159037-c707-4558-bc4d-d656c4a86807
		summarizeBy: none
		sourceColumn: to_release_revision

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"to_release_revision"}]

	column to_revision_fingerprint
		dataType: string
		lineageTag: 948df884-fe4e-4901-82bb-f0c97a85308d
		summarizeBy: none
		sourceColumn: to_revision_fingerprint

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"to_revision_fingerprint"}]

	column gap_days
		dataType: int64
		formatString: 0
		lineageTag: f2f9061b-6224-48ed-be63-e2623c051751
		summarizeBy: none
		sourceColumn: gap_days

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"gap_days"}]

	column matched_start_status
		dataType: string
		lineageTag: 47b5cd06-4c69-46e8-82e8-767f434d63cf
		summarizeBy: none
		sourceColumn: matched_start_status

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"matched_start_status"}]

	column matched_end_population
		dataType: string
		lineageTag: 76749ba5-6e98-4c92-b0ce-07f082d4e562
		summarizeBy: none
		sourceColumn: matched_end_population

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"matched_end_population"}]

	column support_count
		dataType: int64
		formatString: 0
		lineageTag: 0b878d1f-029e-4b74-8eb8-9b94ddadb280
		summarizeBy: none
		sourceColumn: support_count

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"support_count"}]

	column support_denominator_count
		dataType: int64
		formatString: 0
		lineageTag: 729f07de-4523-4be9-a725-8ad640fa22c3
		summarizeBy: none
		sourceColumn: support_denominator_count

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"support_denominator_count"}]

	column support_denominator_id
		dataType: string
		lineageTag: f45017f8-c9b3-4cee-8ac1-24956625e4f2
		summarizeBy: none
		sourceColumn: support_denominator_id

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"support_denominator_id"}]

	column support_share_of_matched_entries
		dataType: string
		lineageTag: fa754f85-55ac-46f2-94cf-30bda880711d
		summarizeBy: none
		sourceColumn: support_share_of_matched_entries

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"support_share_of_matched_entries"}]

	column total_matched_entry_count
		dataType: int64
		formatString: 0
		lineageTag: 5e4cec32-593f-4c17-afef-c8c9ad71b0e4
		summarizeBy: none
		sourceColumn: total_matched_entry_count

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"total_matched_entry_count"}]

	column matched_entry_denominator_id
		dataType: string
		lineageTag: 9818165f-082c-4953-a8ec-8cc5618d0cf0
		summarizeBy: none
		sourceColumn: matched_entry_denominator_id

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"matched_entry_denominator_id"}]

	column total_entrant_count
		dataType: int64
		formatString: 0
		lineageTag: 156fef63-a5ce-495f-879c-80bf81992463
		summarizeBy: none
		sourceColumn: total_entrant_count

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"total_entrant_count"}]

	column total_entrant_denominator_id
		dataType: string
		lineageTag: c18fa08e-1449-491e-917f-9ef052c5825b
		summarizeBy: none
		sourceColumn: total_entrant_denominator_id

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"total_entrant_denominator_id"}]

	column dominant_source_reported_status_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 0432435c-d358-45bf-b6ad-0f723b1c27e0
		summarizeBy: none
		sourceColumn: dominant_source_reported_status_date

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"dominant_source_reported_status_date"}]

		annotation UnderlyingDateTimeDataType = Date

	column dominant_status_date_count
		dataType: int64
		formatString: 0
		lineageTag: 19377eaa-7634-474b-bdb8-3036c68a018d
		summarizeBy: none
		sourceColumn: dominant_status_date_count

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"dominant_status_date_count"}]

	column dominant_status_date_denominator_count
		dataType: int64
		formatString: 0
		lineageTag: c6f63c8b-a436-422c-8844-7efe9874d326
		summarizeBy: none
		sourceColumn: dominant_status_date_denominator_count

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"dominant_status_date_denominator_count"}]

	column dominant_status_date_denominator_id
		dataType: string
		lineageTag: 8cfdfa31-a0ef-4f44-acc9-e900efe12db1
		summarizeBy: none
		sourceColumn: dominant_status_date_denominator_id

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"dominant_status_date_denominator_id"}]

	column dominant_status_date_share
		dataType: double
		formatString: 0.0000
		lineageTag: a72db396-b4f0-4da5-9059-e47abe6755ec
		summarizeBy: none
		sourceColumn: dominant_status_date_share

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"dominant_status_date_share"}]

	column next_from_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: b235a243-bc39-42e0-a2c7-0eb8dcdd6873
		summarizeBy: none
		sourceColumn: next_from_as_of_date

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"next_from_as_of_date"}]

		annotation UnderlyingDateTimeDataType = Date

	column next_to_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 4c0200f0-706b-4e7a-9db8-e24f5aa0f96e
		summarizeBy: none
		sourceColumn: next_to_as_of_date

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"next_to_as_of_date"}]

		annotation UnderlyingDateTimeDataType = Date

	column next_gap_days
		dataType: int64
		formatString: 0
		lineageTag: 0e9b3473-f0e3-47c3-ba4b-f36bd9d1c4c8
		summarizeBy: none
		sourceColumn: next_gap_days

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"next_gap_days"}]

	column next_total_matched_entry_count
		dataType: int64
		formatString: 0
		lineageTag: 46130443-44f1-4077-a5cf-a52fe9bd652f
		summarizeBy: none
		sourceColumn: next_total_matched_entry_count

		annotation CalicoBaseLineage = [{"table_name":"mart_claim_support","column_name":"next_total_matched_entry_count"}]

	partition mart_claim_support = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(PublishedBaseUrl, [RelativePath="exports/mart_claim_support.csv"]), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=false]),
				    Required = {"claim_support_version", "from_as_of_date", "from_release_revision", "from_revision_fingerprint", "to_as_of_date", "to_release_revision", "to_revision_fingerprint", "gap_days", "matched_start_status", "matched_end_population", "support_count", "support_denominator_count", "support_denominator_id", "support_share_of_matched_entries", "total_matched_entry_count", "matched_entry_denominator_id", "total_entrant_count", "total_entrant_denominator_id", "dominant_source_reported_status_date", "dominant_status_date_count", "dominant_status_date_denominator_count", "dominant_status_date_denominator_id", "dominant_status_date_share", "next_from_as_of_date", "next_to_as_of_date", "next_gap_days", "next_total_matched_entry_count"},
				    Shape = if Table.ColumnNames(Headers) <> Required then error "mart_claim_support.source_shape" else Headers,
				    Selected = Table.SelectColumns(Shape, Required, MissingField.Error),
				    Typed = Table.TransformColumnTypes(Selected, {{"claim_support_version", type text}, {"from_as_of_date", type date}, {"from_release_revision", Int64.Type}, {"from_revision_fingerprint", type text}, {"to_as_of_date", type date}, {"to_release_revision", Int64.Type}, {"to_revision_fingerprint", type text}, {"gap_days", Int64.Type}, {"matched_start_status", type text}, {"matched_end_population", type text}, {"support_count", Int64.Type}, {"support_denominator_count", Int64.Type}, {"support_denominator_id", type text}, {"support_share_of_matched_entries", type text}, {"total_matched_entry_count", Int64.Type}, {"matched_entry_denominator_id", type text}, {"total_entrant_count", Int64.Type}, {"total_entrant_denominator_id", type text}, {"dominant_source_reported_status_date", type date}, {"dominant_status_date_count", Int64.Type}, {"dominant_status_date_denominator_count", Int64.Type}, {"dominant_status_date_denominator_id", type text}, {"dominant_status_date_share", type number}, {"next_from_as_of_date", type date}, {"next_to_as_of_date", type date}, {"next_gap_days", Int64.Type}, {"next_total_matched_entry_count", Int64.Type}}, "en-US")
				in
				    Typed

