table mart_publication_status

	column published_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: published_as_of_date
		annotation CalicoBaseLineage = [{"table_name":"mart_publication_status","column_name":"published_as_of_date"}]

	column published_release_revision
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: published_release_revision
		annotation CalicoBaseLineage = [{"table_name":"mart_publication_status","column_name":"published_release_revision"}]

	measure 'Published as-of date' = SELECTEDVALUE(mart_publication_status[published_as_of_date])
		formatString: yyyy-MM-dd
		annotation CalicoBaseLineage = [{"table_name":"mart_publication_status","column_name":"published_as_of_date"}]

	measure 'Published release revision' = SELECTEDVALUE(mart_publication_status[published_release_revision])
		formatString: 0
		annotation CalicoBaseLineage = [{"table_name":"mart_publication_status","column_name":"published_release_revision"}]

	partition mart_publication_status = m
		mode: import
		source =
			let
			    Source = Csv.Document(Web.Contents(PublishedBaseUrl, [RelativePath="exports/mart_publication_status.csv"]), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=false]),
			    Required = {"published_as_of_date", "published_release_revision"},
			    Shape = if Table.ColumnNames(Headers) <> Required then error "publication_status.source_shape" else Headers,
			    Selected = Table.SelectColumns(Shape, Required, MissingField.Error),
			    Typed = Table.TransformColumnTypes(Selected, {{"published_as_of_date", type date}, {"published_release_revision", Int64.Type}}, "en-US")
			in
			    Typed
