table mart_release_quality

	column as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: as_of_date
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"as_of_date"}]

	column release_revision
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: release_revision
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"release_revision"}]

	column revision_fingerprint
		dataType: string
		summarizeBy: none
		sourceColumn: revision_fingerprint
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"revision_fingerprint"}]

	column parser_contract_version
		dataType: string
		summarizeBy: none
		sourceColumn: parser_contract_version
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"parser_contract_version"}]

	column release_health_state
		dataType: string
		summarizeBy: none
		sourceColumn: release_health_state
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"release_health_state"}]

	column release_flag_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: release_flag_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"release_flag_count"}]

	column release_flag_pass_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: release_flag_pass_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"release_flag_pass_count"}]

	column release_flag_review_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: release_flag_review_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"release_flag_review_count"}]

	column release_flag_rule_versions
		dataType: string
		summarizeBy: none
		sourceColumn: release_flag_rule_versions
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"release_flag_rule_versions"}]

	column schema_added_column_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: schema_added_column_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"schema_added_column_count"}]

	column schema_removed_column_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: schema_removed_column_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"schema_removed_column_count"}]

	column schema_type_changed_column_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: schema_type_changed_column_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"schema_type_changed_column_count"}]

	column schema_contract_version
		dataType: string
		summarizeBy: none
		sourceColumn: schema_contract_version
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"schema_contract_version"}]

	column capture_attempted_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: capture_attempted_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"capture_attempted_count"}]

	column capture_succeeded_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: capture_succeeded_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"capture_succeeded_count"}]

	column capture_failed_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: capture_failed_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"capture_failed_count"}]

	column capture_unavailable_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: capture_unavailable_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_quality","column_name":"capture_unavailable_count"}]

	partition mart_release_quality = m
		mode: import
		source =
			let
			    Source = Csv.Document(Web.Contents(PublishedBaseUrl, [RelativePath="exports/mart_release_quality.csv"]), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=false]),
			    Required = {"as_of_date", "release_revision", "revision_fingerprint", "parser_contract_version", "release_health_state", "release_flag_count", "release_flag_pass_count", "release_flag_review_count", "release_flag_rule_versions", "schema_added_column_count", "schema_removed_column_count", "schema_type_changed_column_count", "schema_contract_version", "capture_attempted_count", "capture_succeeded_count", "capture_failed_count", "capture_unavailable_count"},
			    Shape = if Table.ColumnNames(Headers) <> Required then error "mart_release_quality.source_shape" else Headers,
			    Selected = Table.SelectColumns(Shape, Required, MissingField.Error),
			    Typed = Table.TransformColumnTypes(Selected, {{"as_of_date", type date}, {"release_revision", Int64.Type}, {"revision_fingerprint", type text}, {"parser_contract_version", type text}, {"release_health_state", type text}, {"release_flag_count", Int64.Type}, {"release_flag_pass_count", Int64.Type}, {"release_flag_review_count", Int64.Type}, {"release_flag_rule_versions", type text}, {"schema_added_column_count", Int64.Type}, {"schema_removed_column_count", Int64.Type}, {"schema_type_changed_column_count", Int64.Type}, {"schema_contract_version", type text}, {"capture_attempted_count", Int64.Type}, {"capture_succeeded_count", Int64.Type}, {"capture_failed_count", Int64.Type}, {"capture_unavailable_count", Int64.Type}}, "en-US")
			in
			    Typed
