table mart_release_snapshot_metrics

	column as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: as_of_date
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"as_of_date"}]

	column release_revision
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: release_revision
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"release_revision"}]

	column revision_fingerprint
		dataType: string
		summarizeBy: none
		sourceColumn: revision_fingerprint
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"revision_fingerprint"}]

	column parser_contract_version
		dataType: string
		summarizeBy: none
		sourceColumn: parser_contract_version
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"parser_contract_version"}]

	column published_delinquent_category
		dataType: string
		summarizeBy: none
		sourceColumn: published_delinquent_category
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"published_delinquent_category"}]

	column published_delinquent_category_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: published_delinquent_category_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"published_delinquent_category_count"}]

	column keyed_record_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: keyed_record_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"keyed_record_count"}]

	column unkeyed_record_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: unkeyed_record_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"unkeyed_record_count"}]

	column raw_total_record_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: raw_total_record_count
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"raw_total_record_count"}]

	column keyed_coverage_denominator_id
		dataType: string
		summarizeBy: none
		sourceColumn: keyed_coverage_denominator_id
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"keyed_coverage_denominator_id"}]

	column unkeyed_coverage_denominator_id
		dataType: string
		summarizeBy: none
		sourceColumn: unkeyed_coverage_denominator_id
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"unkeyed_coverage_denominator_id"}]

	column keyed_coverage_proportion
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: keyed_coverage_proportion
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"keyed_coverage_proportion"}]

	column keyed_coverage_wilson_95_lower
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: keyed_coverage_wilson_95_lower
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"keyed_coverage_wilson_95_lower"}]

	column keyed_coverage_wilson_95_upper
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: keyed_coverage_wilson_95_upper
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"keyed_coverage_wilson_95_upper"}]

	column unkeyed_coverage_proportion
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: unkeyed_coverage_proportion
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"unkeyed_coverage_proportion"}]

	column unkeyed_coverage_wilson_95_lower
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: unkeyed_coverage_wilson_95_lower
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"unkeyed_coverage_wilson_95_lower"}]

	column unkeyed_coverage_wilson_95_upper
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: unkeyed_coverage_wilson_95_upper
		annotation CalicoBaseLineage = [{"table_name":"mart_release_snapshot_metrics","column_name":"unkeyed_coverage_wilson_95_upper"}]

	partition mart_release_snapshot_metrics = m
		mode: import
		source =
			let
			    Source = Csv.Document(Web.Contents(PublishedBaseUrl, [RelativePath="exports/mart_release_snapshot_metrics.csv"]), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=false]),
			    Required = {"as_of_date", "release_revision", "revision_fingerprint", "parser_contract_version", "published_delinquent_category", "published_delinquent_category_count", "keyed_record_count", "unkeyed_record_count", "raw_total_record_count", "keyed_coverage_denominator_id", "unkeyed_coverage_denominator_id", "keyed_coverage_proportion", "keyed_coverage_wilson_95_lower", "keyed_coverage_wilson_95_upper", "unkeyed_coverage_proportion", "unkeyed_coverage_wilson_95_lower", "unkeyed_coverage_wilson_95_upper"},
			    Shape = if Table.ColumnNames(Headers) <> Required then error "mart_release_snapshot_metrics.source_shape" else Headers,
			    Selected = Table.SelectColumns(Shape, Required, MissingField.Error),
			    Typed = Table.TransformColumnTypes(Selected, {{"as_of_date", type date}, {"release_revision", Int64.Type}, {"revision_fingerprint", type text}, {"parser_contract_version", type text}, {"published_delinquent_category", type text}, {"published_delinquent_category_count", Int64.Type}, {"keyed_record_count", Int64.Type}, {"unkeyed_record_count", Int64.Type}, {"raw_total_record_count", Int64.Type}, {"keyed_coverage_denominator_id", type text}, {"unkeyed_coverage_denominator_id", type text}, {"keyed_coverage_proportion", type number}, {"keyed_coverage_wilson_95_lower", type number}, {"keyed_coverage_wilson_95_upper", type number}, {"unkeyed_coverage_proportion", type number}, {"unkeyed_coverage_wilson_95_lower", type number}, {"unkeyed_coverage_wilson_95_upper", type number}}, "en-US")
			in
			    Typed
