table mart_registry_population_coverage

	column as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: as_of_date
		annotation CalicoBaseLineage = [{"table_name":"mart_registry_population_coverage","column_name":"as_of_date"}]

	column release_revision
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: release_revision
		annotation CalicoBaseLineage = [{"table_name":"mart_registry_population_coverage","column_name":"release_revision"}]

	column revision_fingerprint
		dataType: string
		summarizeBy: none
		sourceColumn: revision_fingerprint
		annotation CalicoBaseLineage = [{"table_name":"mart_registry_population_coverage","column_name":"revision_fingerprint"}]

	column source_list
		dataType: string
		summarizeBy: none
		sourceColumn: source_list
		annotation CalicoBaseLineage = [{"table_name":"mart_registry_population_coverage","column_name":"source_list"}]

	column source_reported_registry_status
		dataType: string
		summarizeBy: none
		sourceColumn: source_reported_registry_status
		annotation CalicoBaseLineage = [{"table_name":"mart_registry_population_coverage","column_name":"source_reported_registry_status"}]

	column coverage_class
		dataType: string
		summarizeBy: none
		sourceColumn: coverage_class
		annotation CalicoBaseLineage = [{"table_name":"mart_registry_population_coverage","column_name":"coverage_class"}]

	column record_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: record_count
		annotation CalicoBaseLineage = [{"table_name":"mart_registry_population_coverage","column_name":"record_count"}]

	partition mart_registry_population_coverage = m
		mode: import
		source =
			let
			    Source = Csv.Document(Web.Contents(PublishedBaseUrl, [RelativePath="exports/mart_registry_population_coverage.csv"]), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=false]),
			    Required = {"as_of_date", "release_revision", "revision_fingerprint", "source_list", "source_reported_registry_status", "coverage_class", "record_count"},
			    Shape = if Table.ColumnNames(Headers) <> Required then error "mart_registry_population_coverage.source_shape" else Headers,
			    Selected = Table.SelectColumns(Shape, Required, MissingField.Error),
			    Typed = Table.TransformColumnTypes(Selected, {{"as_of_date", type date}, {"release_revision", Int64.Type}, {"revision_fingerprint", type text}, {"source_list", type text}, {"source_reported_registry_status", type text}, {"coverage_class", type text}, {"record_count", Int64.Type}}, "en-US")
			in
			    Typed
