table mart_last_renewal_diagnostic

	column from_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: from_as_of_date
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"from_as_of_date"}]

	column from_release_revision
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: from_release_revision
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"from_release_revision"}]

	column from_revision_fingerprint
		dataType: string
		summarizeBy: none
		sourceColumn: from_revision_fingerprint
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"from_revision_fingerprint"}]

	column to_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: to_as_of_date
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"to_as_of_date"}]

	column to_release_revision
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: to_release_revision
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"to_release_revision"}]

	column to_revision_fingerprint
		dataType: string
		summarizeBy: none
		sourceColumn: to_revision_fingerprint
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"to_revision_fingerprint"}]

	column gap_days
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: gap_days
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"gap_days"}]

	column diagnostic_role
		dataType: string
		summarizeBy: none
		sourceColumn: diagnostic_role
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"diagnostic_role"}]

	column measure_name
		dataType: string
		summarizeBy: none
		sourceColumn: measure_name
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"measure_name"}]

	column denominator_definition_id
		dataType: string
		summarizeBy: none
		sourceColumn: denominator_definition_id
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"denominator_definition_id"}]

	column diagnostic_eligible_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: diagnostic_eligible_count
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"diagnostic_eligible_count"}]

	column numerator_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: numerator_count
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"numerator_count"}]

	column denominator_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: denominator_count
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"denominator_count"}]

	column measure_value
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: measure_value
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"measure_value"}]

	column wilson_95_lower
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: wilson_95_lower
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"wilson_95_lower"}]

	column wilson_95_upper
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: wilson_95_upper
		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"wilson_95_upper"}]

	partition mart_last_renewal_diagnostic = m
		mode: import
		source =
			let
			    Source = Csv.Document(Web.Contents(PublishedBaseUrl, [RelativePath="exports/mart_last_renewal_diagnostic.csv"]), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=false]),
			    Required = {"from_as_of_date", "from_release_revision", "from_revision_fingerprint", "to_as_of_date", "to_release_revision", "to_revision_fingerprint", "gap_days", "diagnostic_role", "measure_name", "denominator_definition_id", "diagnostic_eligible_count", "numerator_count", "denominator_count", "measure_value", "wilson_95_lower", "wilson_95_upper"},
			    Shape = if Table.ColumnNames(Headers) <> Required then error "mart_last_renewal_diagnostic.source_shape" else Headers,
			    Selected = Table.SelectColumns(Shape, Required, MissingField.Error),
			    Typed = Table.TransformColumnTypes(Selected, {{"from_as_of_date", type date}, {"from_release_revision", Int64.Type}, {"from_revision_fingerprint", type text}, {"to_as_of_date", type date}, {"to_release_revision", Int64.Type}, {"to_revision_fingerprint", type text}, {"gap_days", Int64.Type}, {"diagnostic_role", type text}, {"measure_name", type text}, {"denominator_definition_id", type text}, {"diagnostic_eligible_count", Int64.Type}, {"numerator_count", Int64.Type}, {"denominator_count", Int64.Type}, {"measure_value", type number}, {"wilson_95_lower", type number}, {"wilson_95_upper", type number}}, "en-US")
			in
			    Typed
