table mart_last_renewal_diagnostic
	lineageTag: 54a93de0-b305-4cab-aab4-073213eb5d2f

	column from_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 6a8a8a4b-f195-45bc-9614-0b1929a1e8e1
		summarizeBy: none
		sourceColumn: from_as_of_date

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"from_as_of_date"}]

		annotation UnderlyingDateTimeDataType = Date

	column from_release_revision
		dataType: int64
		formatString: 0
		lineageTag: 8b680b95-0e81-4564-8779-808770784ffd
		summarizeBy: none
		sourceColumn: from_release_revision

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"from_release_revision"}]

	column from_revision_fingerprint
		dataType: string
		lineageTag: a8052f85-67da-45c0-abd3-f6aba8bed718
		summarizeBy: none
		sourceColumn: from_revision_fingerprint

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"from_revision_fingerprint"}]

	column to_as_of_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 1ad79981-8a19-43a4-ab15-fa9a3c19b215
		summarizeBy: none
		sourceColumn: to_as_of_date

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"to_as_of_date"}]

		annotation UnderlyingDateTimeDataType = Date

	column to_release_revision
		dataType: int64
		formatString: 0
		lineageTag: 7bf59db7-0fc2-403e-9892-96f253941b4d
		summarizeBy: none
		sourceColumn: to_release_revision

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"to_release_revision"}]

	column to_revision_fingerprint
		dataType: string
		lineageTag: 31f2d009-4ebe-4f36-8586-f7f9de220f82
		summarizeBy: none
		sourceColumn: to_revision_fingerprint

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"to_revision_fingerprint"}]

	column gap_days
		dataType: int64
		formatString: 0
		lineageTag: ec1a5fba-1098-4b89-ba9f-d0675d4b2a71
		summarizeBy: none
		sourceColumn: gap_days

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"gap_days"}]

	column diagnostic_role
		dataType: string
		lineageTag: 5b923f69-c858-4d96-8ecc-9efb1266e00a
		summarizeBy: none
		sourceColumn: diagnostic_role

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"diagnostic_role"}]

	column measure_name
		dataType: string
		lineageTag: ba8866d2-e39d-4bfb-a955-a02c4d80fa4a
		summarizeBy: none
		sourceColumn: measure_name

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"measure_name"}]

	column denominator_definition_id
		dataType: string
		lineageTag: 6482c647-8100-4b45-97b4-b9586a0175f8
		summarizeBy: none
		sourceColumn: denominator_definition_id

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"denominator_definition_id"}]

	column diagnostic_eligible_count
		dataType: int64
		formatString: 0
		lineageTag: 240e1724-233f-4f16-b335-987ab6c2c1c3
		summarizeBy: none
		sourceColumn: diagnostic_eligible_count

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"diagnostic_eligible_count"}]

	column numerator_count
		dataType: int64
		formatString: 0
		lineageTag: 13507333-400a-4d04-8f3f-881455300500
		summarizeBy: none
		sourceColumn: numerator_count

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"numerator_count"}]

	column denominator_count
		dataType: int64
		formatString: 0
		lineageTag: 281678d1-a759-4b55-b0f8-03a5c2dcfab5
		summarizeBy: none
		sourceColumn: denominator_count

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"denominator_count"}]

	column measure_value
		dataType: double
		formatString: 0.0000
		lineageTag: ca23dba1-3309-4fd0-8b06-120e2cc69003
		summarizeBy: none
		sourceColumn: measure_value

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"measure_value"}]

	column wilson_95_lower
		dataType: double
		formatString: 0.0000
		lineageTag: b3ee29f5-ad07-4543-bcbc-c0279d229588
		summarizeBy: none
		sourceColumn: wilson_95_lower

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"wilson_95_lower"}]

	column wilson_95_upper
		dataType: double
		formatString: 0.0000
		lineageTag: d316e392-5e28-4493-8af6-b59fb399abc0
		summarizeBy: none
		sourceColumn: wilson_95_upper

		annotation CalicoBaseLineage = [{"table_name":"mart_last_renewal_diagnostic","column_name":"wilson_95_upper"}]

	partition mart_last_renewal_diagnostic = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(PublishedBaseUrl, [RelativePath="exports/mart_last_renewal_diagnostic.csv"]), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=false]),
				    Required = {"from_as_of_date", "from_release_revision", "from_revision_fingerprint", "to_as_of_date", "to_release_revision", "to_revision_fingerprint", "gap_days", "diagnostic_role", "measure_name", "denominator_definition_id", "diagnostic_eligible_count", "numerator_count", "denominator_count", "measure_value", "wilson_95_lower", "wilson_95_upper"},
				    Shape = if Table.ColumnNames(Headers) <> Required then error "mart_last_renewal_diagnostic.source_shape" else Headers,
				    Selected = Table.SelectColumns(Shape, Required, MissingField.Error),
				    Typed = Table.TransformColumnTypes(Selected, {{"from_as_of_date", type date}, {"from_release_revision", Int64.Type}, {"from_revision_fingerprint", type text}, {"to_as_of_date", type date}, {"to_release_revision", Int64.Type}, {"to_revision_fingerprint", type text}, {"gap_days", Int64.Type}, {"diagnostic_role", type text}, {"measure_name", type text}, {"denominator_definition_id", type text}, {"diagnostic_eligible_count", Int64.Type}, {"numerator_count", Int64.Type}, {"denominator_count", Int64.Type}, {"measure_value", type number}, {"wilson_95_lower", type number}, {"wilson_95_upper", type number}}, "en-US")
				in
				    Typed

